config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'searches/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :all_except_current, on: :collection
      end

      resources :questions do
        resources :answers, only: [:show, :index, :create]
      end
    end
  end

  get 'comments/create'

  resources :attachments, only: [:destroy]

  concern :votable do
    member do
      patch :change_rating
      delete :withdraw_rating
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: {commentable: 'questions'}
    resources :subscriptions, only: [:create, :destroy]

    resources :answers, only: [:new, :create, :destroy, :update], concerns: :votable do
      resources :comments, only: :create, defaults: {commentable: 'answers'}
      patch :mark_best, on: :member
    end
  end

  get 'terms_and_conditions', to: 'user_agreements#terms_and_conditions'
  get 'policies', to: 'user_agreements#policies'

  root "questions#index"
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Commentable

  has_many :answers, -> { order(best_answer?: :desc) }, dependent: :destroy
  belongs_to :user
  has_many :subscriptions, dependent: :destroy
  has_many :attachments, as: :attachable

  validates :title, :body, :user_id, presence: true
  validates :title, length: { minimum: 7 }
  validates :body, length: { minimum: 10 }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :update_reputation
  after_create :subscribe_author_for_updates

  searchkick

  scope :posted_today, lambda {
    where("created_at >= ? and created_at <= ?",
          Date.today.beginning_of_day, Date.today.end_of_day)
  }

  private

  def subscribe_author_for_updates
    self.user.subscriptions.create!(question_id: self.id)
  end

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    # respond_with @questions.to_json(include: :answers)
    respond_with @questions, root: 'questions', each_serializer: QuestionCollectionSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with (@question = current_resource_owner.questions.create(question_params))
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :check_ownership, only: [:destroy]
  before_action :build_answer, only: :show

  respond_to :json

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    @answers = @question.answers.order(best_answer?: :desc)
    respond_with @question
  end

  def new
    @question = current_user.questions.new
  end

  def create
    @question = current_user.questions.create(question_params)
    if @question.save
      PrivatePub.publish_to("/questions", question: @question.to_json, users_email: @question.user.email.to_json)
    end
    respond_with @question
  end

  def edit
  end

  def update
    if @question.update(question_params)
      flash.now[:notice] = "Question has been updated!"
    else
      render status: :unprocessable_entity
    end
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.new
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end

  def check_ownership
    current_user.author?(@question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def trigger_subscription(question)
    subscription = current_user.subscriptions.find_by(question_id: @question.id)
    if subscription
      link_to 'Unsubscribe', question_subscription_path(@question, subscription), class: 'btn btn-primary trigger_question_subscription', remote: true, method: :delete
    else
      link_to 'Subscribe', question_subscriptions_path(@question), class: 'btn btn-primary trigger_question_subscription', remote: true, method: :post
    end
  end
end

app/views/questions/_answers.html.slim
-@question.answers.each do |answer|
  p= answer.body
  - if current_user && current_user.author?(answer)
    = button_to 'Delete My Answer', [@question, answer], method: :delete, class: "btn btn-danger btn-sm"

app/views/questions/_form.html.slim
= simple_form_for @question, html: {id: "edit-question-#{@question.id}"}, remote: true do |f|
  div id="question_errors"
    = f.input :title, label: "Title"
    = f.input :body, label: "Question"
    h3 Attachments:
    - if current_user && current_user.author?(@question)
      #attachments
        = f.simple_fields_for :attachments do |attachment|
          = render '/attachments/attachment_fields', f: attachment
      .links
        = link_to_add_association 'Add Attachment', f, :attachments, partial: "/attachments/attachment_fields"
  = f.submit 'Ask'

app/views/questions/_question.html.slim
div id="#{dom_id(question)}" class="card"
  div.card-block
    = render partial: "shared/rating", locals: {entry: question, polymorphic_path_args: @question}
    h1.card-title = question.title
    p.card-text = question.body.html_safe
    #subscription_section
      = render partial:  "subscriptions/subscription_trigger", question: question
    p Attchments:
    ul
      - question.attachments.each do |a|
        div id="attachment_#{a.id}"
          li  = link_to a.file.identifier, a.file.url
          - if current_user && current_user.author?(@question)
            = link_to "Delete File", attachment_path(a), method: :delete, remote: true
    = render "form"

    - if current_user && current_user.author?(@question)
      = button_to 'Delete Question', "", method: :delete, class: "btn btn-danger btn-lg"
      = link_to 'Edit Question', "", class: "btn btn-primary btn-sm", id: "trigger_question_edit_form", data: {question_id: @question.id}

app/views/questions/create.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('#question_body').before('<%= j message %>')
  <% end %>
<% else %>
  <% publish_to "/questions" do %>
    $('#main-question-list').append('<%= j render @question %>');
  <% end %>
  $('#question_body').val('')
  $("#flash").html("<%= j render 'shared/notice_line' %>")
<% end %>

app/views/questions/index.html.slim
div.row
  div.col-lg-12.col-md-12.col-sm-12.col-xs-12.heading_and_call_to_action
    div.col-lg-1.col-md-1.col-sm-6.col-xs-6
      - if can?( :create, Question)
        div
          = link_to "Ask Question", new_question_path, class: "btn btn-primary btn-lg active"
    div.col-lg-9.col-md-9.col-sm-9.col-xs-12
      h1[style="text-align: center;"]
        | All Questions
.main-container.center
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    div.table-responsive
      table.table.table-hover.table-striped.table-bordered#main-question-list
        thead
          tr
            th
              | Title
            th
              | Author
        tbody
          - @questions.each do |q|
            tr
              td
                = link_to q.title, question_path(q)
              td
                = q.user.email

  = subscribe_to "/questions"

app/views/questions/new.html.slim
= simple_form_for @question do |f|
  p
    = f.input :title
  p
    = f.input :body
  p Attachments:
  p
    #attachments
    = f.simple_fields_for :attachments, @question.attachments.build do |a|
      = render '/attachments/attachment_fields', f: a
      .links
        = link_to_add_association 'Add Attachment', f, :attachments, partial: "/attachments/attachment_fields"
  p
    = f.submit 'Ask'

app/views/questions/show.html.slim
- cache @question do
  .show-container
    .question-container
      = render @question
      div id="question_#{@question.id}_comments"
        = render @question.comments
        = subscribe_to "/comments"
      - if current_user
        .comment_form
          = render 'shared/comment_form', commentable: @question, path_arguments: [@question], id: "question_#{@question.id}_comment_form"

    .answers
      = render @answers

  = simple_form_for [@question, @answer], remote: true do |f|
    = f.input :body, label: 'My Answer'
    h3 Attachments:
    #attachments
    = f.simple_fields_for :attachments, @answer.attachments.build do |attachment|
      = render '/attachments/attachment_fields', f: attachment
    .links
      = link_to_add_association 'Attach File', f, :attachments, partial: "/attachments/attachment_fields"
    = f.submit 'Answer'

  = subscribe_to "/question/#{@question.id}/answers"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('#question_errors').html('<%= j message %>')
  <% end %>
<% else %>
  <% if remotipart_submitted? %>
    $('.question-container').html("<%= j "#{render @question}" %>");
    $("#flash").html("<%= j "#{render 'shared/notice_line'}" %>")
  <% else %>
    $('.question-container').html("<%= j render @question %>");
    $("#flash").html("<%= j render 'shared/notice_line' %>")
  <% end %>
<% end %>