config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'searches/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :all_except_current, on: :collection
      end

      resources :questions do
        resources :answers, only: [:show, :index, :create]
      end
    end
  end

  get 'comments/create'

  resources :attachments, only: [:destroy]

  concern :votable do
    member do
      patch :change_rating
      delete :withdraw_rating
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: {commentable: 'questions'}
    resources :subscriptions, only: [:create, :destroy]

    resources :answers, only: [:new, :create, :destroy, :update], concerns: :votable do
      resources :comments, only: :create, defaults: {commentable: 'answers'}
      patch :mark_best, on: :member
    end
  end

  get 'terms_and_conditions', to: 'user_agreements#terms_and_conditions'
  get 'policies', to: 'user_agreements#policies'

  root "questions#index"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable

  validates :body, presence: true, length: { minimum: 20 }
  validates :question_id, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :update_reputation, on: :create
  after_create :notify_subscribers, on: :create

  searchkick

  def mark_best!
    transaction do
      question.answers.update_all(best_answer?: false)
      update(best_answer?: true)
    end
  end

  private

  def notify_subscribers
    SendNotificationsJob.perform_later(self)
  end

  def update_reputation
    CalculateReputationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [:create, :mark_best]
  before_action :get_question, only: [:create, :update, :destroy, :mark_best]
  before_action :get_answer, only: [:update, :destroy, :mark_best]
  before_action :check_ownership, only: [:destroy]
  before_action :check_if_can_mark_best, only: [:mark_best]

  respond_to :js

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_user))
    @answer.save
    respond_with(@answer, location: @question)
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def update
    if @answer.update(answer_params)
      flash.now[:notice] = "Answer has been updated"
    else
      render status: :unprocessable_entity
    end
  end

  def mark_best
    @answers = @question.answers
    @answer.mark_best!
    flash[:notice] = "You have picked best answer!"
  end

  private

  def get_question
    @question = Question.find(params[:question_id])
  end

  def get_answer
    @answer = @question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end

  def check_ownership
    unless current_user.author?(@answer)
      respond_to do |format|
        format.html {redirect_to @question, notice: 'Not your entry'}
      end
    end
  end

  def check_if_can_mark_best
    unless current_user.author?(@answer.question)
      respond_to do |format|
        format.html {redirect_to @question, notice: 'Not your entry'}
      end
    end
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: [:index, :create]

  authorize_resource

  def index
    respond_with @question.answers, root: "answers", each_serializer: AnswerSerializer
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_resource_owner))
    # respond_with :api, :v1, :question, @answer
    # respond_with @answer
    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div.card.card-block.answer-card
    div id="answer-#{dom_id(answer)}" class="#{'best_answer' if answer.best_answer?}"
      h4.card-title = answer.body
      = render partial: "shared/rating", locals: {entry: answer, polymorphic_path_args: [@question, answer]}
      = render answer.comments
      div id="answer_#{answer.id}_comments"
      - if current_user
        = render 'shared/comment_form', commentable: answer, path_arguments: [answer.question, answer], id: "#answer_#{answer.id}_comment_form"
      ul
        - answer.attachments.each do |at|
          div id="attachment_#{ at.id}"
            li= link_to at.file.identifier, at.file.url
            - if current_user && current_user.author?(answer)
              = link_to "Delete File", attachment_path(at), method: :delete, remote: true
      - if current_user && current_user.author?(@question)
        - if !answer.best_answer?
          div id="mark_best_answer#{answer.id}"
            = link_to "Mark Best!", mark_best_question_answer_path(@question, answer), remote: true, method: :patch
      - if current_user && current_user.author?(answer)
        = link_to "Edit Answer", "",  class: "edit-answer-link", data: { answer_id: answer.id }
        = simple_form_for [@question, answer], html: {  id: "edit-answer-#{answer.id}"}, remote: true do |f|
          = f.label :body, "Edit my Answer"
          = f.text_area :body
          div id="answer_#{answer.id}_attachments"
          = f.simple_fields_for :attachments do |attachment|
            = render '/attachments/attachment_fields', f: attachment
          .links
            = link_to_add_association 'Attach File', f, :attachments, partial: "/attachments/attachment_fields"
          .answer-errors
          = f.submit "Edit"
        = button_to 'Delete My Answer', [@question, answer], remote: true, method: :delete, class: "btn btn-danger btn-sm"

app/views/answers/_form.html.slim
= simple_form_for [@question, @answer], remote: @question.persisted? ? true : false, html: { id: "edit-answer-#{answer.id}"} do |form|
  .edit-answer
    = form.input :body, label: "New Answer", id: "form_#{dom_id(answer)}"
    = form.submit answer.new_record? ? 'Submit answer' : 'Update answer'

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('#answer_body').before('<%= j message %>')
  <% end %>
<% else %>
  <% publish_to "/question/#{@question.id}/answers" do %>
    $('.answers').append('<%= j render @answer %>');
  <% end %>
  $('#answer_body').val('')
  $("#flash").html("<%= j render 'shared/notice_line' %>")
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= dom_id(@answer) %>').remove();
$("#flash").html("<%= j render 'shared/notice_line' %>")

app/views/answers/mark_best.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('#answer_body').before('<%= j message %>')
  <% end %>
<% else %>
  $('.answers').html('<%= j render @answers %>');
  $("#flash").html("<%= j render 'shared/notice_line' %>")
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('#answer_body').before('<%= j message %>')
  <% end %>
<% else %>
  <% if remotipart_submitted? %>
    $('#answer-answer_<%= @answer.id %>').html("<%= j "#{render @answer}" %>")
  <% else %>
    $('#answer-answer_<%= @answer.id %>').html('<%= j render @answer %>');
  <% end %>
<% end %>