config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'searches/index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :all_except_current, on: :collection
      end

      resources :questions do
        resources :answers, only: [:show, :index, :create]
      end
    end
  end

  get 'comments/create'

  resources :attachments, only: [:destroy]

  concern :votable do
    member do
      patch :change_rating
      delete :withdraw_rating
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :questions, concerns: :votable do
    resources :comments, only: :create, defaults: {commentable: 'questions'}
    resources :subscriptions, only: [:create, :destroy]

    resources :answers, only: [:new, :create, :destroy, :update], concerns: :votable do
      resources :comments, only: :create, defaults: {commentable: 'answers'}
      patch :mark_best, on: :member
    end
  end

  get 'terms_and_conditions', to: 'user_agreements#terms_and_conditions'
  get 'policies', to: 'user_agreements#policies'

  root "questions#index"
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-full.navbar-dark.bg-inverse
  div.row
    div.col-lg-12.col-md-12.col-sm-12.col-xs-12
      .navbar-brand
        = link_to "Stackish", root_path, style: "color: white;"
      div.col-lg-4.col-md-4.col-sm-4.col-xs-4.offset-lg-5
        = form_tag searches_index_path, method: :get, class: "form-inline float-xs-right" do
          = text_field_tag :q, nil, class: "form-control", id: "search_word_field"
          = select_tag :by, options_for_select(["Question", "Answer", "Comment", "User"]), include_blank: true, class: "form-control", id: "model-type-select"
          = submit_tag "Search", class: "btn btn-outline-success"
      div.col-lg-1.col-md-1.col-sm-1.col-xs-1
      - if user_signed_in?
        div[style="float: right;"]
          = link_to('Logout', destroy_user_session_path, :method => :delete, class: "btn btn-primary")
      - else
        div[style="float: right;"]
          = link_to('Login', new_user_session_path, class: "btn btn-primary")
          = link_to('Sign Up', new_user_registration_path, class: "btn btn-primary")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container-fluid">
    <div id="flash">
      <% if notice.present? %>
        <%= render partial: "shared/notice_line" %>
      <% end %>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </div>

</body>
</html>